"""add_knowledge_graph_tables

Revision ID: 1b878edf97ae
Revises: 
Create Date: 2026-05-06 03:31:17.386516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b878edf97ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('source_file_path', sa.String(), nullable=False),
    sa.Column('imported_module', sa.String(), nullable=False),
    sa.Column('imported_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('resolved_file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qualified', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_table('call_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=True),
    sa.Column('callee_id', sa.Integer(), nullable=True),
    sa.Column('call_site_file', sa.String(), nullable=True),
    sa.Column('call_site_line', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['callee_id'], ['symbols.id'], ),
    sa.ForeignKeyConstraint(['caller_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('issues', sa.Column('symbol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'symbols', ['symbol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'symbol_id')
    op.drop_table('call_edges')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_table('import_edges')
    # ### end Alembic commands ###
